// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAI9Hin0Zql6xCna9_2ZQ0RNskskfK9Mw',
    appId: '1:73042147583:web:5d1b56737a2383e10b34ca',
    messagingSenderId: '73042147583',
    projectId: 'artwork-6218f',
    authDomain: 'artwork-6218f.firebaseapp.com',
    storageBucket: 'artwork-6218f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWSiYFDvDOT61C7lBbyHz4y9CDL0EH_IY',
    appId: '1:73042147583:android:c21ea07a213e1bae0b34ca',
    messagingSenderId: '73042147583',
    projectId: 'artwork-6218f',
    storageBucket: 'artwork-6218f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo3TNc7lK2aVVlxYfEe46IZYK8qgl_hZw',
    appId: '1:73042147583:ios:27482156b4b30efa0b34ca',
    messagingSenderId: '73042147583',
    projectId: 'artwork-6218f',
    storageBucket: 'artwork-6218f.appspot.com',
    iosBundleId: 'com.example.artwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo3TNc7lK2aVVlxYfEe46IZYK8qgl_hZw',
    appId: '1:73042147583:ios:84c9ef01ec7b9fcd0b34ca',
    messagingSenderId: '73042147583',
    projectId: 'artwork-6218f',
    storageBucket: 'artwork-6218f.appspot.com',
    iosBundleId: 'com.example.artwork.RunnerTests',
  );
}
